shopping:
  replicaCount: 2
  image:
    repository: catarena
    tag: latest
customer:
  replicaCount: 2
  image:
    repository: catarena
    tag: latest
products:
  replicaCount: 2
  image:
    repository: catarena
    tag: 
gateway:
  image:
    repository: catarena
    tag: latest

# Cấu hình Ingress
ingress:
  enabled: true
  className: "nginx"
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

  hosts:
    - host: nt548.com
      paths:
         - path: /customer
           serviceName: customer-service 
           port: 80
         - path: /shopping
           serviceName: shopping-service
           port: 80
         - path: /
           serviceName: products-service
           pathType: Prefix

service:
  port: 80

fullnameOverride: "nt548"