shopping:
  replicaCount: 2
  image:
    repository: catarena/shopping
    tag: latest
customer:
  replicaCount: 2
  image:
    repository: catarena/customer
    tag: latest
products:
  replicaCount: 2
  image:
    repository: catarena/products
    tag: latest

# Cấu hình Ingress
ingress:
  enabled: true
  className: "nginx"
  
  annotations:
    kubernetes.io/ingress.class: nginx

  hosts:
    - host: nt548.com
      paths:
         - path: /customer
           serviceName: customer-service 
           pathType: Prefix
           port: 80
         - path: /shopping
           serviceName: shopping-service
           pathType: Prefix
           port: 80
         - path: /
           serviceName: products-service
           pathType: Prefix
           port: 80

service:
  port: 80
