shopping:
  replicaCount: 2
  image:
    repository: catarena/shopping
    tag: 21
customer:
  replicaCount: 2
  image:
    repository: catarena/customer
    tag: 3
products:
  replicaCount: 2
  image:
    repository: catarena/products
    tag: 22

# Cấu hình Ingress
ingress:
  enabled: true
  className: "nginx"
  
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/server-alias: "www.cookial.site"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

  tls:
    - secretName: cookial-tls-prod
      hosts:
        - cookial.site
        - www.cookial.site
  hosts:
    - host: cookial.site
      paths:
         - path: /customer(/|$)(.*)
           serviceName: customer-service 
           pathType: ImplementationSpecific
           port: 80
         - path: /shopping(/|$)(.*)
           serviceName: shopping-service
           pathType: ImplementationSpecific
           port: 80
         - path: /()(.*)
           serviceName: products-service
           pathType: ImplementationSpecific
           port: 80

service:
  port: 80
