apiVersion: v1
kind: Pod
spec:
  containers:
  - name: nodejs
    image: node:18-alpine
    command: ['sleep']
    args: ['9999999']
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ['sleep']
    args: ['9999999']
    volumeMounts:
    - name: kaniko-secret-volume 
      mountPath: /kaniko/.docker 
  - name: trivy
    image: aquasec/trivy:latest
    command: ['sleep']
    args: ['9999999']
    volumeMounts:
    - name: trivy-cache
      mountPath: /root/.cache/
  volumes:
  - name: kaniko-secret-volume   
    secret:
      secretName: regcred    
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: trivy-cache
    emptyDir: {}