apiVersion: v1
kind: ConfigMap
metadata:
  name: nt548-configmap-general
  namespace: nt548
data:
  EXCHANGE_NAME: 'ONLINE_STORE'
  MONGODB_URI: 'mongodb://mongodb-service'
  MSG_QUEUE_URL: 'amqp://rabbitmq-service'