apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: {{ .Values.customer.replicaCount }}
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: "{{- .Values.customer.image.repository }}: {{- .Values.customer.image.tag }}"
        resources:
          requests:
            cpu: "250m"       
            memory: "512Mi"   
          limits:
            cpu: "500m"   
            memory: "1024Mi"
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nt548-configmap
              key: CUSTOMER_PORT
        envFrom:
        - configMapRef:
            name: nt548-configmap-general
        - secretRef:
            name: nt548-secret-general
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          periodSeconds: 3
          failureThreshold: 40  
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001