apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: {{ .Values.customer.replicaCount }}
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: "{{- .Values.customer.image.repository }}: {{- .Values.customer.image.tag }}"
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nt548-configmap-general
              key: CUSTOMER_PORT
        envFrom:
        - configMapRef:
            name: nt548-configmap-general
        - secretRef:
            name: nt548-secret-general
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001