apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: nt548
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongodb-storage
  resources:
    requests:
      storage: 1Gi