apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-deployment
  labels:
    app: shopping
spec:
  replicas: {{ .Values.shopping.replicaCount }}
  selector:
    matchLabels:
      app: shopping
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
      - name: shopping
        image: "{{- .Values.shopping.image.repository }}: {{- .Values.shopping.image.tag }}"
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: nt548-configmap-general
              key: CUSTOMER_PORT
        envFrom:
        - configMapRef:
            name: nt548-configmap-general
        - secretRef:
            name: nt548-secret-general
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  selector:
    app: shopping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003