# 1. Load module ở dòng đầu tiên
load_module modules/ngx_otel_module.so;

worker_processes 4;
events { worker_connections 1024; }

http {
    # 2. Cấu hình OTel
    otel_exporter {
        endpoint jaeger:4317; # Đảm bảo port 4317 gRPC của Jaeger đã mở
    }
    otel_service_name nginx-gateway;
    otel_trace on;
    otel_trace_context propagate;

    upstream customer_servers {
            server customer:8001;
        }
    server {
        listen 80;
        charset utf-8;

        location / {
            otel_span_name "Products-Service-Route";
            proxy_pass http://products:8002;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        location ~ ^/shopping {
            otel_span_name "Shopping-Service-Route";
            rewrite ^/shopping/(.*) /$1 break;
            proxy_pass http://shopping:8003;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }

        location /customer {
            otel_span_name "Customer-Service-Route";
            rewrite ^/customer/(.*)$ /$1 break;
            proxy_pass http://customer:8001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }
    }
}