---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nt548-secret-general
  namespace: nt548
spec:
  encryptedData:
    APP_SECRET: AgAJZFmpLWMzX8ZIRVjQ0YrJrFD2Uk4HCCF3mqRpoJwdpY07Ht7MZbjPfWkAQldsl/sXP77Pbb3Wq5gFMYrVthA1tCjog3hq2Qh2kDJcSZfVLvnNkF4dYEXtcbH1XKmKHJzhfYqtKAplNOJ+u1C5edcVpD2ZyebdKC209tQUUIIWewQRwGOX5W6DlozBboQedd48P98F70gvRMrkTg03rHqQO5YwT3ELTMqmjL9njqV+meKRmk2zhkzJ25/EIVJtAlAL1wnKTp5dJaf4EcCe8NTXWD5IhLjGgxzNScmwMSYHCfP2NwNfmXLYMS+u4jQ0tlGDybdLTAbvQm3h6wclDB25d/8EmqJ+t3Z/ncHFhmxZMB8v4xx5VKPFxivUneyaiHmlEe99BiwaBNHqlcxxLboJZiDm1wVCdERcZQolFM3rqxqQ9qB+YvOpTQb2eXK6AAP1DCYyn6lCb6+PVzKRAGLMbH0iDD6M2stu7wEHn6+razI0WLOmFLxyrzDWXQNE0x7VmwmXWTPvc4/t6o0YAUpnPa3CDg+pn3x7PziH+3ovQHHywQOp7KIkpMtVpuEFPXOo2w8PwLjEn2AeuGq7VNjVHt1sznBeV749n6rhQZKFXoRRbHxqD/mii/qsJF+3x65wvbBDGDRQUwHGUxRAb0DTpmjhUA9MmJjwy/Rmsvmf5j6k/ZLB7uwn1D0KlzPcUnlAMnyrkNqzHagBAuw6Jg+mGbcmhw==
    MONGODB_URI: AgBIEKf1Aqhq3KQzFSq1kO5p8JJaVLoXgydmIHvVHecdU6F2FrCN8+dGjyGVQIx/b0FEk+S9DMVxlRXXPJrzqrKn49FQE6Xf4n344J/zgX3hEgHBRZRDUNHDsZcykzJjrk9yG0N4TjJ1ppTy0o77dn+8kn1gZgzgTTm0lED58ihcqPGBCAN+8yfQgzvSRY1MRz+RB1C0ESAJnS1WAn1cWxxT7+ic3uIPcyqlCJmaUrC54CrhkZBK0Ulxmm+cC+GcID+7zCYBUQZlDZm1rVDQzHQb3+fiPjLe+0DlkdghCDFs7p44zsNq3VKe4f/XnxUvenaDghQZmVBSE9WCBos7WX2VlVd3FnZm6/gZr3EWNUVd3H4oUuACgyYZjm4iqp9Myr1Xc64CnBfwg4DSKh6gMvO3hKBegbJXvaHLECwEGzmJohROn4nHmWtLweQnu0Kn3XG0yjgmIzflQXdcVCDiJ5Zb7S0nRDuU/shVFEfN+7drA/hoAkW1UC8NJeU1Bdclo5fVHLP2DYa9gH0Pb3NeHrG/jbGYO1D0hGj3+dDB697Bdny7F/Q6dviSHIKw9W7zQSrmkto6RNEzIK/B0gWK6V2A7GHEYE/OghrZJ+yyxHeR0f8VdKbxPthYeESdb3fth5NQRq//MalqkM12uHolYZecseI15RFFO5WjFW1bjdOcsCPNcL7SdLgpeOoOZs3awmmjBTf840lz7lkJsFsfIzHUrnEdiGvmnKaRnDRzJ6hE7hsnXrp6DaSIO6X3o4nmgLwgCZ2CdXRIsCqzuKJ1TTr54CyPiSZQBZfqGFja+h0+KLf8CsnqL4skXMO6HOr9Q5gktqd9ey4=
  template:
    metadata:
      name: nt548-secret-general
      namespace: nt548
    type: Opaque
