---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nt548-secret
  namespace: nt548
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgAK7569Ii+vqDnKDrYrO1nvfKkbCqy6fdF0NwBPyA0EQ3kyBbu9QHa5c4FvIuGMknQkXTVzlI3Nbc3dxjjWRDvNveHotsBSP/CEy7WXWu9Ux8Is2UVvGKGcRFI+s1vKM5q9Wt1r0ZslCyW3UgX6R+HZ0qnsKJ6UZU1j8iFZMtSSBus3vIPqIODKnFrxLtfjQsrGMBNhw81vjN6J1fbV6SUQl73FXBTTwEic0q1ml0tEuQLqaJQjyXFnrTt9zvTfyx79UbUSMoNf/UysEHLXBZFXvpvxO4dIDLY1TQMp+73XFoOtPjTb1jfxJagGhB4hAw5SJ2Fuau+vmybDaqxR4indSX9Nem1uALIt/0w7aKQOuyGNnjg2asRbypfcdowFzXyXZWOTgUSMm44HPooC/O7PAKH7lD7QH6oWULMCrrOVOmpDRBFAQ9lZvoCnFlsI8Tt61P4YwCUgH4JPQHuKRQ1H8atChNd6+6jilWbTMD/vwdeLfNO2Efz0Y6WXIQOm5CUfNqgz5o+PKlJH9mBILTnc6ibKKtCBW0iar5xarM+iJy5wv2sQiFhabAB6La56Ct6afA+7bgVlwqi/Sh0vmHcG/nt4CfbCDW0GjE17+8EvhjVPUrMXk5ZK69PWoxAXzIuGUoSkYnnlRbHlZ5lfS2V2oShdQ0ege2HsXYrC5lbyTqbDO7rgUxSk6q6mfF9XPQZFsGD0Qg9FN58ru+H7rAyhrMiFACgVWvg=
    MONGO_INITDB_ROOT_USERNAME: AgB23CodMUfHhQpOJccWBO36bmczTkVgCrq2EPysGyG6/IMHPkLMFwoY8sMrv4J91xeA/UVyXO4upfOWuh8HeFmggYowupK/Lynr3g8ImBNa/lGR+9gzGXcBXxeAZ9U0EEOSNiC9/w+J54hsy+3yREbUyy22MZqnFyp1dlhVsPbh2A1sp4Fpn0ymJJ+N7DS2VF8aGJMu7cgvPDaqSLdJXihVP972mnbispL3RmI831uXfyf7GCXWN+gEVZqA42eQwib+fXQgzHIqTiF7Ep0RMCIZh7MeneOFUCZrgdLyRSRhHZ3WLX7xeFB+VKhF5G7db3jo3QLuuiR+E9n4RlaRGA2Xs3qgXh/YYuIIqV0ZUagop7WZWheoEi7neqt/s64jvTfnyhxg79mWlIn5ZnY1Ax4mm2V7IfBSEjO5h/BeRCzWcWUhGq3hc1TFqTtQ1PH0oCp22lau9LWgnpi0kcE3Zfwpuok2ZyL+eGbiVuac/jGAxWr21Ykp2t0g/uxTmS1qJGwHb7SLKNY86ovOLzbzgGtZ/LDV0Gd5MipaXbuKJ4AeCtEnW+kAQDO3DwtzPersrPZ58q6mXiAcUif9Ut89GjbMkYr9XBf545t8v9mhF5rDQv2jGx6QX9G7f7a/gtDJTpaKhHW7h0jkN2tEOOiHrnLodGaCSfNjCh1qAOzEXEW9SLqHPncqGHTBIBGHXyb2sMIXvyaRGyy5dkjM3N+2baEzlaSw9p0Br4M=
  template:
    metadata:
      name: nt548-secret
      namespace: nt548
    type: Opaque
